spring.application.name=restful-web-services
spring.h2.console.enabled=true
#wait for data source finishing initializing before running commands on it
spring.jpa.defer-datasource-initialization=true 
spring.datasource.url=jdbc:h2:mem:testdb

management.endpoints.web.exposure.include=*

logging.level.org.springframework=info
